// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project2

#include "../ui.h"

void ui_MainScreen_screen_init(void)
{
ui_MainScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_MainScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Container9 = lv_obj_create(ui_MainScreen);
lv_obj_remove_style_all(ui_Container9);
lv_obj_set_width( ui_Container9, lv_pct(100));
lv_obj_set_height( ui_Container9, lv_pct(100));
lv_obj_set_align( ui_Container9, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Container9,LV_FLEX_FLOW_ROW_WRAP);
lv_obj_set_flex_align(ui_Container9, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_Container9, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Container2 = lv_obj_create(ui_Container9);
lv_obj_remove_style_all(ui_Container2);
lv_obj_set_height( ui_Container2, 150);
lv_obj_set_width( ui_Container2, lv_pct(100));
lv_obj_set_align( ui_Container2, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Container2,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Container2, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_FlushButton = lv_btn_create(ui_Container2);
lv_obj_set_width( ui_FlushButton, 100);
lv_obj_set_height( ui_FlushButton, 100);
lv_obj_set_align( ui_FlushButton, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_FlushButton,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_FlushButton, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_add_flag( ui_FlushButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_FlushButton, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_FlushButton, 25, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_FlushButton, lv_color_hex(0x3C3C3C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_FlushButton, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_FlushImage = lv_img_create(ui_FlushButton);
lv_img_set_src(ui_FlushImage, &ui_img_2089747144);
lv_obj_set_width( ui_FlushImage, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_FlushImage, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_FlushImage, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_FlushImage, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_FlushImage, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_FlushLabel = lv_label_create(ui_FlushButton);
lv_obj_set_width( ui_FlushLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_FlushLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_FlushLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_FlushLabel,"Flush");
lv_obj_set_style_text_font(ui_FlushLabel, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_StartButton = lv_btn_create(ui_Container2);
lv_obj_set_width( ui_StartButton, 100);
lv_obj_set_height( ui_StartButton, 100);
lv_obj_set_align( ui_StartButton, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_StartButton,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_StartButton, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_add_flag( ui_StartButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_StartButton, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_StartButton, 25, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_StartButton, lv_color_hex(0x3C3C3C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_StartButton, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_StartImage = lv_img_create(ui_StartButton);
lv_img_set_src(ui_StartImage, &ui_img_1544916161);
lv_obj_set_width( ui_StartImage, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_StartImage, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_StartImage, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_StartImage, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_StartImage, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_StartLabel = lv_label_create(ui_StartButton);
lv_obj_set_width( ui_StartLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_StartLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_StartLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_StartLabel,"Start");
lv_obj_set_style_text_font(ui_StartLabel, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_StopButton = lv_btn_create(ui_Container2);
lv_obj_set_width( ui_StopButton, 100);
lv_obj_set_height( ui_StopButton, 100);
lv_obj_set_align( ui_StopButton, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_StopButton,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_StopButton, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_add_flag( ui_StopButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_StopButton, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_StopButton, 25, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_StopButton, lv_color_hex(0x3C3C3C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_StopButton, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_StopImage = lv_img_create(ui_StopButton);
lv_img_set_src(ui_StopImage, &ui_img_515815694);
lv_obj_set_width( ui_StopImage, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_StopImage, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_StopImage, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_StopImage, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_StopImage, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_StopLabel = lv_label_create(ui_StopButton);
lv_obj_set_width( ui_StopLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_StopLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_StopLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_StopLabel,"Stop");
lv_obj_set_style_text_font(ui_StopLabel, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel1 = lv_obj_create(ui_Container2);
lv_obj_set_width( ui_Panel1, 200);
lv_obj_set_height( ui_Panel1, 100);
lv_obj_set_align( ui_Panel1, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Panel1,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Panel1, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_Panel1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Panel1, 25, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0x3C3C3C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Panel1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container11 = lv_obj_create(ui_Panel1);
lv_obj_remove_style_all(ui_Container11);
lv_obj_set_width( ui_Container11, lv_pct(100));
lv_obj_set_height( ui_Container11, lv_pct(50));
lv_obj_set_align( ui_Container11, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Container11,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Container11, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_Container11, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_TimerImage = lv_img_create(ui_Container11);
lv_img_set_src(ui_TimerImage, &ui_img_timer_png);
lv_obj_set_width( ui_TimerImage, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TimerImage, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_TimerImage, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_TimerImage, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_TimerImage, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_TimerImage,150);

ui_TimerLabel = lv_label_create(ui_Container11);
lv_obj_set_width( ui_TimerLabel, 70);
lv_obj_set_height( ui_TimerLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_TimerLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_TimerLabel,"0:00");
lv_obj_set_style_text_align(ui_TimerLabel, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_TimerLabel, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TimerPrefixLabel = lv_label_create(ui_Container11);
lv_obj_set_width( ui_TimerPrefixLabel, 25);
lv_obj_set_height( ui_TimerPrefixLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_TimerPrefixLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_TimerPrefixLabel,"s");
lv_obj_set_style_text_align(ui_TimerPrefixLabel, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_TimerPrefixLabel, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container8 = lv_obj_create(ui_Container11);
lv_obj_remove_style_all(ui_Container8);
lv_obj_set_width( ui_Container8, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Container8, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Container8, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Container8, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_TimerResetButton = lv_btn_create(ui_Container8);
lv_obj_set_width( ui_TimerResetButton, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TimerResetButton, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_TimerResetButton, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_TimerResetButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_TimerResetButton, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_TimerResetButton, lv_color_hex(0x393C39), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_TimerResetButton, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_blend_mode(ui_TimerResetButton, LV_BLEND_MODE_NORMAL, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TimerResetImage = lv_img_create(ui_TimerResetButton);
lv_img_set_src(ui_TimerResetImage, &ui_img_951525100);
lv_obj_set_width( ui_TimerResetImage, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TimerResetImage, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_TimerResetImage, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_TimerResetImage, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_TimerResetImage, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Container12 = lv_obj_create(ui_Panel1);
lv_obj_remove_style_all(ui_Container12);
lv_obj_set_width( ui_Container12, lv_pct(100));
lv_obj_set_height( ui_Container12, lv_pct(50));
lv_obj_set_align( ui_Container12, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Container12,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Container12, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_Container12, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_ScaleImage = lv_img_create(ui_Container12);
lv_img_set_src(ui_ScaleImage, &ui_img_weight_png);
lv_obj_set_width( ui_ScaleImage, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ScaleImage, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_ScaleImage, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ScaleImage, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ScaleImage, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_ScaleImage,150);

ui_ScaleLabel = lv_label_create(ui_Container12);
lv_obj_set_width( ui_ScaleLabel, 70);
lv_obj_set_height( ui_ScaleLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_ScaleLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_ScaleLabel,"888.8");
lv_obj_set_style_text_align(ui_ScaleLabel, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_ScaleLabel, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ScalePrefixLabel = lv_label_create(ui_Container12);
lv_obj_set_width( ui_ScalePrefixLabel, 25);
lv_obj_set_height( ui_ScalePrefixLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_ScalePrefixLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_ScalePrefixLabel,"g");
lv_obj_set_style_text_align(ui_ScalePrefixLabel, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_ScalePrefixLabel, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container15 = lv_obj_create(ui_Container12);
lv_obj_remove_style_all(ui_Container15);
lv_obj_set_width( ui_Container15, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Container15, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Container15, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Container15, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_ScaleResetButton = lv_btn_create(ui_Container15);
lv_obj_set_width( ui_ScaleResetButton, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ScaleResetButton, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_ScaleResetButton, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ScaleResetButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ScaleResetButton, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ScaleResetButton, lv_color_hex(0x393C39), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ScaleResetButton, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_blend_mode(ui_ScaleResetButton, LV_BLEND_MODE_NORMAL, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ScaleResetImage = lv_img_create(ui_ScaleResetButton);
lv_img_set_src(ui_ScaleResetImage, &ui_img_951525100);
lv_obj_set_width( ui_ScaleResetImage, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ScaleResetImage, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_ScaleResetImage, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ScaleResetImage, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ScaleResetImage, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Container3 = lv_obj_create(ui_Container9);
lv_obj_remove_style_all(ui_Container3);
lv_obj_set_height( ui_Container3, 30);
lv_obj_set_width( ui_Container3, lv_pct(100));
lv_obj_set_x( ui_Container3, -275 );
lv_obj_set_y( ui_Container3, 44 );
lv_obj_set_flex_flow(ui_Container3,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Container3, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_Container3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Container3, lv_color_hex(0x232323), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Container3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container4 = lv_obj_create(ui_Container3);
lv_obj_remove_style_all(ui_Container4);
lv_obj_set_width( ui_Container4, 15);
lv_obj_set_height( ui_Container4, 30);
lv_obj_set_align( ui_Container4, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Container4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_SerialImage = lv_img_create(ui_Container3);
lv_img_set_src(ui_SerialImage, &ui_img_1495795081);
lv_obj_set_width( ui_SerialImage, 24);
lv_obj_set_height( ui_SerialImage, 24);
lv_obj_set_align( ui_SerialImage, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_SerialImage, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_SerialImage, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_SerialPrefixLabel = lv_label_create(ui_Container3);
lv_obj_set_width( ui_SerialPrefixLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SerialPrefixLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_SerialPrefixLabel, 25 );
lv_obj_set_y( ui_SerialPrefixLabel, 0 );
lv_obj_set_align( ui_SerialPrefixLabel, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_SerialPrefixLabel,"System Status :");

ui_Container1 = lv_obj_create(ui_Container3);
lv_obj_remove_style_all(ui_Container1);
lv_obj_set_width( ui_Container1, 5);
lv_obj_set_height( ui_Container1, 30);
lv_obj_set_align( ui_Container1, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_SerialLabel = lv_label_create(ui_Container3);
lv_obj_set_width( ui_SerialLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SerialLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_SerialLabel, 25 );
lv_obj_set_y( ui_SerialLabel, 0 );
lv_obj_set_align( ui_SerialLabel, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_SerialLabel,"_");

ui_GoToSettingButton = lv_btn_create(ui_MainScreen);
lv_obj_set_width( ui_GoToSettingButton, 28);
lv_obj_set_height( ui_GoToSettingButton, 28);
lv_obj_set_x( ui_GoToSettingButton, -1 );
lv_obj_set_y( ui_GoToSettingButton, -1 );
lv_obj_set_align( ui_GoToSettingButton, LV_ALIGN_BOTTOM_RIGHT );
lv_obj_add_flag( ui_GoToSettingButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_GoToSettingButton, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_GoToSettingButton, lv_color_hex(0x1A1A1A), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_GoToSettingButton, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_GoToSettingButton, &ui_img_80803761, LV_PART_MAIN | LV_STATE_DEFAULT );

ui_BluetoothImage1 = lv_img_create(ui_MainScreen);
lv_img_set_src(ui_BluetoothImage1, &ui_img_420894227);
lv_obj_set_width( ui_BluetoothImage1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_BluetoothImage1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_BluetoothImage1, -2 );
lv_obj_set_y( ui_BluetoothImage1, 2 );
lv_obj_set_align( ui_BluetoothImage1, LV_ALIGN_TOP_RIGHT );
lv_obj_add_state( ui_BluetoothImage1, LV_STATE_DISABLED );     /// States
lv_obj_add_flag( ui_BluetoothImage1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_BluetoothImage1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_img_opa(ui_BluetoothImage1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_recolor(ui_BluetoothImage1, lv_color_hex(0x4040FF), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_recolor_opa(ui_BluetoothImage1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor(ui_BluetoothImage1, lv_color_hex(0x6B7280), LV_PART_MAIN| LV_STATE_DISABLED);
lv_obj_set_style_img_recolor_opa(ui_BluetoothImage1, 255, LV_PART_MAIN| LV_STATE_DISABLED);

lv_obj_add_event_cb(ui_FlushButton, ui_event_FlushButton, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_StartButton, ui_event_StartButton, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_StopButton, ui_event_StopButton, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_TimerResetButton, ui_event_TimerResetButton, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ScaleResetButton, ui_event_ScaleResetButton, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_GoToSettingButton, ui_event_GoToSettingButton, LV_EVENT_ALL, NULL);

}
