// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project2

#include "../ui.h"

void ui_SettingScreen_screen_init(void)
{
ui_SettingScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_SettingScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Container5 = lv_obj_create(ui_SettingScreen);
lv_obj_remove_style_all(ui_Container5);
lv_obj_set_width( ui_Container5, lv_pct(100));
lv_obj_set_height( ui_Container5, lv_pct(100));
lv_obj_set_align( ui_Container5, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Container5,LV_FLEX_FLOW_ROW_WRAP);
lv_obj_set_flex_align(ui_Container5, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_Container5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Container6 = lv_obj_create(ui_Container5);
lv_obj_remove_style_all(ui_Container6);
lv_obj_set_height( ui_Container6, 150);
lv_obj_set_width( ui_Container6, lv_pct(100));
lv_obj_set_align( ui_Container6, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Container6,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Container6, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_Container6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Panel2 = lv_obj_create(ui_Container6);
lv_obj_set_width( ui_Panel2, 580);
lv_obj_set_height( ui_Panel2, 100);
lv_obj_set_align( ui_Panel2, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Panel2,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Panel2, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_Panel2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Panel2, 25, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0x3C3C3C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Panel2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container7 = lv_obj_create(ui_Panel2);
lv_obj_remove_style_all(ui_Container7);
lv_obj_set_width( ui_Container7, lv_pct(100));
lv_obj_set_height( ui_Container7, lv_pct(50));
lv_obj_set_align( ui_Container7, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Container7,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Container7, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_Container7, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Container16 = lv_obj_create(ui_Container7);
lv_obj_remove_style_all(ui_Container16);
lv_obj_set_width( ui_Container16, 80);
lv_obj_set_height( ui_Container16, 50);
lv_obj_set_align( ui_Container16, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Container16, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_BacklightImage = lv_img_create(ui_Container16);
lv_img_set_src(ui_BacklightImage, &ui_img_light_png);
lv_obj_set_width( ui_BacklightImage, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_BacklightImage, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_BacklightImage, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_BacklightImage, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_BacklightImage, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_BacklightImage,150);

ui_BacklightSlider = lv_slider_create(ui_Container7);
lv_slider_set_value( ui_BacklightSlider, 50, LV_ANIM_OFF);
if (lv_slider_get_mode(ui_BacklightSlider)==LV_SLIDER_MODE_RANGE ) lv_slider_set_left_value( ui_BacklightSlider, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_BacklightSlider, 350);
lv_obj_set_height( ui_BacklightSlider, 20);
lv_obj_set_align( ui_BacklightSlider, LV_ALIGN_CENTER );
lv_obj_set_style_bg_color(ui_BacklightSlider, lv_color_hex(0x585858), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_BacklightSlider, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_BacklightSlider, lv_color_hex(0x393C39), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_BacklightSlider, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_BacklightSlider, 5, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_BacklightSlider, lv_color_hex(0x747474), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_BacklightSlider, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_BacklightSlider, lv_color_hex(0x393C39), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_BacklightSlider, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_BacklightSlider, 3, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_BacklightSlider, LV_BORDER_SIDE_FULL, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_BacklightSlider, lv_color_hex(0x393C39), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_BacklightSlider, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_outline_width(ui_BacklightSlider, 3, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_outline_pad(ui_BacklightSlider, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_BacklightSlider, lv_color_hex(0x8C8C8C), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_BacklightSlider, 255, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_BacklightSlider, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_BacklightSlider, 255, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_BacklightSlider, 5, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_BacklightLabel = lv_label_create(ui_Container7);
lv_obj_set_width( ui_BacklightLabel, 80);
lv_obj_set_height( ui_BacklightLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_BacklightLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_BacklightLabel,"100 %");
lv_obj_set_style_text_align(ui_BacklightLabel, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_BacklightLabel, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ScaleSlider = lv_obj_create(ui_Panel2);
lv_obj_remove_style_all(ui_ScaleSlider);
lv_obj_set_width( ui_ScaleSlider, lv_pct(100));
lv_obj_set_height( ui_ScaleSlider, lv_pct(50));
lv_obj_set_align( ui_ScaleSlider, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_ScaleSlider,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_ScaleSlider, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_ScaleSlider, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Container17 = lv_obj_create(ui_ScaleSlider);
lv_obj_remove_style_all(ui_Container17);
lv_obj_set_width( ui_Container17, 80);
lv_obj_set_height( ui_Container17, 50);
lv_obj_set_align( ui_Container17, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Container17, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_ScaleImage1 = lv_img_create(ui_Container17);
lv_img_set_src(ui_ScaleImage1, &ui_img_weight_png);
lv_obj_set_width( ui_ScaleImage1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ScaleImage1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_ScaleImage1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ScaleImage1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ScaleImage1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_ScaleImage1,150);

ui_PresetWeightSlight = lv_slider_create(ui_ScaleSlider);
lv_slider_set_range(ui_PresetWeightSlight, 0,50);
lv_slider_set_value( ui_PresetWeightSlight, 36, LV_ANIM_OFF);
if (lv_slider_get_mode(ui_PresetWeightSlight)==LV_SLIDER_MODE_RANGE ) lv_slider_set_left_value( ui_PresetWeightSlight, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_PresetWeightSlight, 350);
lv_obj_set_height( ui_PresetWeightSlight, 20);
lv_obj_set_x( ui_PresetWeightSlight, 35 );
lv_obj_set_y( ui_PresetWeightSlight, 2 );
lv_obj_set_align( ui_PresetWeightSlight, LV_ALIGN_CENTER );
lv_obj_set_style_bg_color(ui_PresetWeightSlight, lv_color_hex(0x585858), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PresetWeightSlight, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_PresetWeightSlight, lv_color_hex(0x393C39), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_PresetWeightSlight, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_PresetWeightSlight, 5, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_PresetWeightSlight, lv_color_hex(0x747474), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PresetWeightSlight, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_PresetWeightSlight, lv_color_hex(0x393C39), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_PresetWeightSlight, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_PresetWeightSlight, 3, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_PresetWeightSlight, lv_color_hex(0x393C39), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_PresetWeightSlight, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_outline_width(ui_PresetWeightSlight, 2, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_outline_pad(ui_PresetWeightSlight, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_PresetWeightSlight, lv_color_hex(0x8C8C8C), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PresetWeightSlight, 255, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_PresetWeightSlight, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_PresetWeightSlight, 255, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_PresetWeightSlight, 5, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_PresetWeightLabel = lv_label_create(ui_ScaleSlider);
lv_obj_set_width( ui_PresetWeightLabel, 80);
lv_obj_set_height( ui_PresetWeightLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_PresetWeightLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_PresetWeightLabel,"50 g");
lv_obj_set_style_text_align(ui_PresetWeightLabel, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_PresetWeightLabel, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container10 = lv_obj_create(ui_Container5);
lv_obj_remove_style_all(ui_Container10);
lv_obj_set_height( ui_Container10, 30);
lv_obj_set_width( ui_Container10, lv_pct(100));
lv_obj_set_x( ui_Container10, -275 );
lv_obj_set_y( ui_Container10, 44 );
lv_obj_set_flex_flow(ui_Container10,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Container10, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_Container10, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Container10, lv_color_hex(0x232323), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Container10, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container13 = lv_obj_create(ui_Container10);
lv_obj_remove_style_all(ui_Container13);
lv_obj_set_width( ui_Container13, 15);
lv_obj_set_height( ui_Container13, 30);
lv_obj_set_align( ui_Container13, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Container13, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_SerialImage1 = lv_img_create(ui_Container10);
lv_img_set_src(ui_SerialImage1, &ui_img_1495795081);
lv_obj_set_width( ui_SerialImage1, 24);
lv_obj_set_height( ui_SerialImage1, 24);
lv_obj_set_align( ui_SerialImage1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_SerialImage1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_SerialImage1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_SerialPrefixLabel1 = lv_label_create(ui_Container10);
lv_obj_set_width( ui_SerialPrefixLabel1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SerialPrefixLabel1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_SerialPrefixLabel1, 25 );
lv_obj_set_y( ui_SerialPrefixLabel1, 0 );
lv_obj_set_align( ui_SerialPrefixLabel1, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_SerialPrefixLabel1,"System Status :");

ui_Container14 = lv_obj_create(ui_Container10);
lv_obj_remove_style_all(ui_Container14);
lv_obj_set_width( ui_Container14, 5);
lv_obj_set_height( ui_Container14, 30);
lv_obj_set_align( ui_Container14, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Container14, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_SerialLabel1 = lv_label_create(ui_Container10);
lv_obj_set_width( ui_SerialLabel1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SerialLabel1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_SerialLabel1, 25 );
lv_obj_set_y( ui_SerialLabel1, 0 );
lv_obj_set_align( ui_SerialLabel1, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_SerialLabel1,"_");

ui_ReturnFromSettingButton = lv_btn_create(ui_SettingScreen);
lv_obj_set_width( ui_ReturnFromSettingButton, 28);
lv_obj_set_height( ui_ReturnFromSettingButton, 28);
lv_obj_set_x( ui_ReturnFromSettingButton, -1 );
lv_obj_set_y( ui_ReturnFromSettingButton, -1 );
lv_obj_set_align( ui_ReturnFromSettingButton, LV_ALIGN_BOTTOM_RIGHT );
lv_obj_add_flag( ui_ReturnFromSettingButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ReturnFromSettingButton, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ReturnFromSettingButton, lv_color_hex(0x1A1A1A), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ReturnFromSettingButton, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_ReturnFromSettingButton, &ui_img_return_png, LV_PART_MAIN | LV_STATE_DEFAULT );

ui_BluetoothImage2 = lv_img_create(ui_SettingScreen);
lv_img_set_src(ui_BluetoothImage2, &ui_img_420894227);
lv_obj_set_width( ui_BluetoothImage2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_BluetoothImage2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_BluetoothImage2, -2 );
lv_obj_set_y( ui_BluetoothImage2, 2 );
lv_obj_set_align( ui_BluetoothImage2, LV_ALIGN_TOP_RIGHT );
lv_obj_add_state( ui_BluetoothImage2, LV_STATE_CHECKED | LV_STATE_DISABLED );     /// States
lv_obj_add_flag( ui_BluetoothImage2, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_BluetoothImage2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_img_opa(ui_BluetoothImage2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_recolor(ui_BluetoothImage2, lv_color_hex(0x4040FF), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_recolor_opa(ui_BluetoothImage2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor(ui_BluetoothImage2, lv_color_hex(0x6B7280), LV_PART_MAIN| LV_STATE_DISABLED);
lv_obj_set_style_img_recolor_opa(ui_BluetoothImage2, 255, LV_PART_MAIN| LV_STATE_DISABLED);

lv_obj_add_event_cb(ui_BacklightSlider, ui_event_BacklightSlider, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_PresetWeightSlight, ui_event_PresetWeightSlight, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ReturnFromSettingButton, ui_event_ReturnFromSettingButton, LV_EVENT_ALL, NULL);

}
