// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project2

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_MainScreen
void ui_MainScreen_screen_init(void);
lv_obj_t *ui_MainScreen;
lv_obj_t *ui_Container9;
lv_obj_t *ui_Container2;
void ui_event_FlushButton( lv_event_t * e);
lv_obj_t *ui_FlushButton;
lv_obj_t *ui_FlushImage;
lv_obj_t *ui_FlushLabel;
void ui_event_StartButton( lv_event_t * e);
lv_obj_t *ui_StartButton;
lv_obj_t *ui_StartImage;
lv_obj_t *ui_StartLabel;
void ui_event_StopButton( lv_event_t * e);
lv_obj_t *ui_StopButton;
lv_obj_t *ui_StopImage;
lv_obj_t *ui_StopLabel;
lv_obj_t *ui_Panel1;
lv_obj_t *ui_Container11;
lv_obj_t *ui_TimerImage;
lv_obj_t *ui_TimerLabel;
lv_obj_t *ui_TimerPrefixLabel;
lv_obj_t *ui_Container8;
void ui_event_TimerResetButton( lv_event_t * e);
lv_obj_t *ui_TimerResetButton;
lv_obj_t *ui_TimerResetImage;
lv_obj_t *ui_Container12;
lv_obj_t *ui_ScaleImage;
lv_obj_t *ui_ScaleLabel;
lv_obj_t *ui_ScalePrefixLabel;
lv_obj_t *ui_Container15;
void ui_event_ScaleResetButton( lv_event_t * e);
lv_obj_t *ui_ScaleResetButton;
lv_obj_t *ui_ScaleResetImage;
lv_obj_t *ui_Container3;
lv_obj_t *ui_Container4;
lv_obj_t *ui_SerialImage;
lv_obj_t *ui_SerialPrefixLabel;
lv_obj_t *ui_Container1;
lv_obj_t *ui_SerialLabel;
void ui_event_GoToSettingButton( lv_event_t * e);
lv_obj_t *ui_GoToSettingButton;
lv_obj_t *ui_BluetoothImage1;


// SCREEN: ui_SettingScreen
void ui_SettingScreen_screen_init(void);
lv_obj_t *ui_SettingScreen;
lv_obj_t *ui_Container5;
lv_obj_t *ui_Container6;
lv_obj_t *ui_Panel2;
lv_obj_t *ui_Container7;
lv_obj_t *ui_Container16;
lv_obj_t *ui_BacklightImage;
void ui_event_BacklightSlider( lv_event_t * e);
lv_obj_t *ui_BacklightSlider;
lv_obj_t *ui_BacklightLabel;
lv_obj_t *ui_ScaleSlider;
lv_obj_t *ui_Container17;
lv_obj_t *ui_ScaleImage1;
void ui_event_PresetWeightSlight( lv_event_t * e);
lv_obj_t *ui_PresetWeightSlight;
lv_obj_t *ui_PresetWeightLabel;
lv_obj_t *ui_Container10;
lv_obj_t *ui_Container13;
lv_obj_t *ui_SerialImage1;
lv_obj_t *ui_SerialPrefixLabel1;
lv_obj_t *ui_Container14;
lv_obj_t *ui_SerialLabel1;
void ui_event_ReturnFromSettingButton( lv_event_t * e);
lv_obj_t *ui_ReturnFromSettingButton;
lv_obj_t *ui_BluetoothImage2;
lv_obj_t *ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

void ui_event_GoToSettingButton( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_SettingScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 100, 0, &ui_SettingScreen_screen_init);
}
}

void ui_event_ReturnFromSettingButton( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_MainScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 100, 0, &ui_MainScreen_screen_init);
}
}

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), true, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_MainScreen_screen_init();
ui_SettingScreen_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_MainScreen);
}
