// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project2

#ifndef _SQUARELINE_PROJECT2_UI_H
#define _SQUARELINE_PROJECT2_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_MainScreen
void ui_MainScreen_screen_init(void);
extern lv_obj_t *ui_MainScreen;
extern lv_obj_t *ui_Container9;
extern lv_obj_t *ui_Container2;
void ui_event_FlushButton( lv_event_t * e);
extern lv_obj_t *ui_FlushButton;
extern lv_obj_t *ui_FlushImage;
extern lv_obj_t *ui_FlushLabel;
void ui_event_StartButton( lv_event_t * e);
extern lv_obj_t *ui_StartButton;
extern lv_obj_t *ui_StartImage;
extern lv_obj_t *ui_StartLabel;
void ui_event_StopButton( lv_event_t * e);
extern lv_obj_t *ui_StopButton;
extern lv_obj_t *ui_StopImage;
extern lv_obj_t *ui_StopLabel;
extern lv_obj_t *ui_Panel1;
extern lv_obj_t *ui_Container11;
extern lv_obj_t *ui_TimerImage;
extern lv_obj_t *ui_TimerLabel;
extern lv_obj_t *ui_TimerPrefixLabel;
extern lv_obj_t *ui_Container8;
void ui_event_TimerResetButton( lv_event_t * e);
extern lv_obj_t *ui_TimerResetButton;
extern lv_obj_t *ui_TimerResetImage;
extern lv_obj_t *ui_Container12;
extern lv_obj_t *ui_ScaleImage;
extern lv_obj_t *ui_ScaleLabel;
extern lv_obj_t *ui_ScalePrefixLabel;
extern lv_obj_t *ui_Container15;
void ui_event_ScaleResetButton( lv_event_t * e);
extern lv_obj_t *ui_ScaleResetButton;
extern lv_obj_t *ui_ScaleResetImage;
extern lv_obj_t *ui_Container3;
extern lv_obj_t *ui_Container4;
extern lv_obj_t *ui_SerialImage;
extern lv_obj_t *ui_SerialPrefixLabel;
extern lv_obj_t *ui_Container1;
extern lv_obj_t *ui_SerialLabel;
void ui_event_GoToSettingButton( lv_event_t * e);
extern lv_obj_t *ui_GoToSettingButton;
extern lv_obj_t *ui_BluetoothImage1;
// SCREEN: ui_SettingScreen
void ui_SettingScreen_screen_init(void);
extern lv_obj_t *ui_SettingScreen;
extern lv_obj_t *ui_Container5;
extern lv_obj_t *ui_Container6;
extern lv_obj_t *ui_Panel2;
extern lv_obj_t *ui_Container7;
extern lv_obj_t *ui_Container16;
extern lv_obj_t *ui_BacklightImage;
void ui_event_BacklightSlider( lv_event_t * e);
extern lv_obj_t *ui_BacklightSlider;
extern lv_obj_t *ui_BacklightLabel;
extern lv_obj_t *ui_ScaleSlider;
extern lv_obj_t *ui_Container17;
extern lv_obj_t *ui_ScaleImage1;
void ui_event_PresetWeightSlight( lv_event_t * e);
extern lv_obj_t *ui_PresetWeightSlight;
extern lv_obj_t *ui_PresetWeightLabel;
extern lv_obj_t *ui_Container10;
extern lv_obj_t *ui_Container13;
extern lv_obj_t *ui_SerialImage1;
extern lv_obj_t *ui_SerialPrefixLabel1;
extern lv_obj_t *ui_Container14;
extern lv_obj_t *ui_SerialLabel1;
void ui_event_ReturnFromSettingButton( lv_event_t * e);
extern lv_obj_t *ui_ReturnFromSettingButton;
extern lv_obj_t *ui_BluetoothImage2;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE( ui_img_2089747144);   // assets/waterdrops-bold.png
LV_IMG_DECLARE( ui_img_1233654078);   // assets/tea-cup-broken.png
LV_IMG_DECLARE( ui_img_1683789101);   // assets/close-square-broken.png
LV_IMG_DECLARE( ui_img_1530343224);   // assets/alarm-broken.png
LV_IMG_DECLARE( ui_img_97407014);   // assets/refresh-broken.png
LV_IMG_DECLARE( ui_img_1992534686);   // assets/weigher-broken.png
LV_IMG_DECLARE( ui_img_2251575);   // assets/alt-arrow-right-broken.png
LV_IMG_DECLARE( ui_img_setting_png);   // assets/setting.png
LV_IMG_DECLARE( ui_img_249472744);   // assets/bluetooth-circle-broken.png
LV_IMG_DECLARE( ui_img_806972598);   // assets/lightbulb-minimalistic-broken.png
LV_IMG_DECLARE( ui_img_1111506397);   // assets/return (1).png




void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
